services:
  mysql:
    image: mysql:8.0
    container_name: jobportal-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobportal
    ports:
      - "3306:3306"
    volumes:
      - jobportal-mysql-data:/var/lib/mysql

volumes:
  jobportal-mysql-data:
